import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../theme/app_theme.dart';
import '../routes.dart';
import '../widgets/bottom_nav_bar.dart';
import '../widgets/common_widgets.dart';
import '../models/user_model.dart';
import '../services/providers.dart';
import '../services/sensor_service.dart';
import '../services/weather_service.dart';

class MainDashboard extends StatefulWidget {
  const MainDashboard({super.key});

  @override
  State<MainDashboard> createState() => _MainDashboardState();
}

class _MainDashboardState extends State<MainDashboard> {
  WeatherData? _weather;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<SensorProvider>().startListening();
      context.read<AlertProvider>().startListening();
      context.read<HistoryProvider>().loadProduction('weekly');
      _loadWeather();
    });
  }

  Future<void> _loadWeather() async {
    final weather = await WeatherService.getOuagaWeather();
    if (mounted) {
      setState(() => _weather = weather);
    }
  }

  @override
  Widget build(BuildContext context) {
    final auth = context.watch<AuthProvider>();
    final sensorProv = context.watch<SensorProvider>();
    final isFrench = context.watch<LocaleProvider>().isFrench;
    final cs = Theme.of(context).colorScheme;

    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.surface,
      appBar: _buildAppBar(context),
      body: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(
          AppTheme.containerPadding,
          24,
          AppTheme.containerPadding,
          120,
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Hero Greeting
            _buildGreetingSection(auth.user),
            const SizedBox(height: 32),

            // Biodigester Visual
            const BiodigesterVisual(height: 220),
            const SizedBox(height: 32),

            _buildQuickActions(context),
            const SizedBox(height: 24),

            // ESP8266 Status Card
            const ESP8266StatusCard(),
            const SizedBox(height: 12),

            // Supabase Status Card
            const SupabaseStatusCard(),
            const SizedBox(height: 32),

            // Simulation indicator
            if (sensorProv.isSimulation)
              Container(
                width: double.infinity,
                margin: const EdgeInsets.only(bottom: 12),
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                decoration: BoxDecoration(
                  color: const Color(0xFFFFF8E1),
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: const Color(0xFFF57F17).withValues(alpha: 0.3)),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.science, size: 16, color: Color(0xFFF57F17)),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        isFrench ? 'Mode simulation - Données générées par le jumeau numérique' : 'Simulation mode - Data generated by digital twin',
                        style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w500, color: Color(0xFFF57F17)),
                      ),
                    ),
                  ],
                ),
              ),

            // Sensor Grid (real-time from SensorProvider)
            Consumer<SensorProvider>(
              builder: (ctx, sensorProv, _) {
                final reading = sensorProv.latestReading;
                if (reading != null && reading.temperature > 0) {
                  return _buildLiveSensorGrid(reading);
                }
                if (sensorProv.isLoading) {
                  return const Padding(
                    padding: EdgeInsets.symmetric(vertical: 24),
                    child: Center(child: CircularProgressIndicator()),
                  );
                }
                return Padding(
                  padding: const EdgeInsets.symmetric(vertical: 24),
                  child: Center(
                    child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Icon(Icons.sensors_off, size: 48, color: cs.onSurfaceVariant.withValues(alpha: 0.5)),
                        const SizedBox(height: 12),
                        Text(
                          isFrench ? 'Aucun capteur connecté' : 'No sensors connected',
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w600,
                            color: cs.onSurface,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          isFrench ? 'Connectez votre ESP8266 pour voir les données en temps réel.' : 'Connect your ESP8266 to see real-time data.',
                          style: TextStyle(fontSize: 13, color: cs.onSurfaceVariant),
                          textAlign: TextAlign.center,
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
            const SizedBox(height: 32),

            // Biogas Production Card
            const BiogasProductionCard(),
            const SizedBox(height: 12),

            // Energy Impact Card
            const EnergyImpactCard(),
            const SizedBox(height: 32),

            // Daily Insight
            _buildDailyInsight(context),
          ],
        ),
      ),
      bottomNavigationBar: const BottomNavBar(currentIndex: 0),
    );
  }

  PreferredSizeWidget _buildAppBar(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return PreferredSize(
      preferredSize: const Size.fromHeight(64),
      child: Container(
        color: Theme.of(context).colorScheme.surfaceContainerHighest,
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsets.symmetric(
              horizontal: AppTheme.containerPadding,
              vertical: AppTheme.baseSpacing,
            ),
            child: Row(
              children: [
                const CircleAvatar(
                  radius: 20,
                  backgroundColor: AppTheme.primaryContainer,
                  child: Icon(Icons.eco, color: AppTheme.onPrimary, size: 20),
                ),
                const SizedBox(width: 12),
                const Text(
                  'BioDigit',
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.w500,
                    color: AppTheme.primary,
                  ),
                ),
                const Spacer(),
                IconButton(
                  onPressed: () =>
                      Navigator.pushNamed(context, AppRoutes.notifications),
                  icon: Icon(Icons.notifications, color: cs.onSurfaceVariant),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildGreetingSection(UserModel? user) {
    final isFrench = context.watch<LocaleProvider>().isFrench;
    final displayName = user?.fullName.trim().isNotEmpty == true
        ? user!.fullName
        : (isFrench ? 'Ferme Plateau Central' : 'Plateau Central Farm');

    return LayoutBuilder(
      builder: (context, constraints) {
        final cs = Theme.of(context).colorScheme;
        final narrow = constraints.maxWidth < 560;
        final weather = Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          decoration: BoxDecoration(
            color: Theme.of(context).colorScheme.surfaceContainerHighest.withValues(alpha: 0.7),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withValues(alpha: 0.3)),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(
                _weather?.weatherIcon ?? Icons.wb_sunny,
                color: _weather?.weatherColor ?? AppTheme.secondary,
                size: 28,
              ),
              const SizedBox(width: 12),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Ouagadougou, BF',
                    style: TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w500,
                      color: cs.onSurface,
                    ),
                  ),
                  Text(
                    _weather != null ? '${_weather!.temperature.round()}°C' : '--°C',
                    style: TextStyle(
                      fontSize: 22,
                      fontWeight: FontWeight.w500,
                      color: _weather?.weatherColor ?? AppTheme.primary,
                    ),
                  ),
                ],
              ),
            ],
          ),
        );

        if (narrow) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                isFrench ? 'Bienvenue, $displayName' : 'Welcome, $displayName',
                style: TextStyle(
                  fontSize: 28,
                  height: 36 / 28,
                  fontWeight: FontWeight.w600,
                  color: Theme.of(context).colorScheme.onSurface,
                ),
              ),
              const SizedBox(height: 12),
              weather,
              const SizedBox(height: 12),
              Text(
                isFrench ? 'Votre système de biodigesteur est suivi en temps réel.' : 'Your biodigester system is monitored in real-time.',
                style: TextStyle(
                  fontSize: 14,
                  color: Theme.of(context).colorScheme.onSurfaceVariant,
                ),
              ),
            ],
          );
        }

        return Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Flexible(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    isFrench ? 'Bienvenue, $displayName' : 'Welcome, $displayName',
                    style: TextStyle(
                      fontSize: 28,
                      height: 36 / 28,
                      fontWeight: FontWeight.w600,
                      color: Theme.of(context).colorScheme.onSurface,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    isFrench ? 'Votre système de biodigesteur est suivi en temps réel.' : 'Your biodigester system is monitored in real-time.',
                    style: TextStyle(
                      fontSize: 14,
                      color: Theme.of(context).colorScheme.onSurfaceVariant,
                    ),
                  ),
                ],
              ),
            ),
            weather,
          ],
        );
      },
    );
  }

  Widget _buildQuickActions(BuildContext context) {
    final isFrench = context.watch<LocaleProvider>().isFrench;
    final actions = [
      _QuickAction(Icons.sensors, isFrench ? 'Direct' : 'Live', AppRoutes.liveMonitoring, AppTheme.primary),
      _QuickAction(Icons.notifications_active, isFrench ? 'Alertes' : 'Alerts', AppRoutes.alerts, AppTheme.secondary),
      _QuickAction(Icons.history, isFrench ? 'Historique' : 'History', AppRoutes.history, AppTheme.tertiary),
      _QuickAction(Icons.person, isFrench ? 'Profil' : 'Profile', AppRoutes.userProfile, const Color(0xFF2E7D32)),
    ];

    return LayoutBuilder(
      builder: (context, constraints) {
        final columns = constraints.maxWidth >= 720 ? 4 : 2;
        if (constraints.maxWidth < 420) {
          return Column(
            children: actions
                .map(
                  (action) => Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: InkWell(
                      onTap: () => Navigator.pushNamed(context, action.route),
                      borderRadius: BorderRadius.circular(18),
                      child: Container(
                        width: double.infinity,
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: Theme.of(context).colorScheme.surfaceContainerHighest,
                          borderRadius: BorderRadius.circular(18),
                          border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withValues(alpha: 0.3)),
                        ),
                        child: Row(
                          children: [
                            Container(
                              padding: const EdgeInsets.all(10),
                              decoration: BoxDecoration(
                                color: action.color.withValues(alpha: 0.10),
                                borderRadius: BorderRadius.circular(14),
                              ),
                              child: Icon(action.icon, color: action.color, size: 22),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: Text(
                                action.label,
                                style: TextStyle(fontSize: 14, fontWeight: FontWeight.w600, color: AppTheme.text(context)),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                )
                .toList(),
          );
        }

        return GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          itemCount: actions.length,
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: columns,
            crossAxisSpacing: 12,
            mainAxisSpacing: 12,
            childAspectRatio: 2.4,
          ),
          itemBuilder: (context, index) {
            final cs = Theme.of(context).colorScheme;
            final action = actions[index];
            return InkWell(
              onTap: () => Navigator.pushNamed(context, action.route),
              borderRadius: BorderRadius.circular(18),
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Theme.of(context).colorScheme.surfaceContainerHighest,
                  borderRadius: BorderRadius.circular(18),
                  border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withValues(alpha: 0.3)),
                ),
                child: Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(10),
                      decoration: BoxDecoration(
                        color: action.color.withValues(alpha: 0.10),
                        borderRadius: BorderRadius.circular(14),
                      ),
                      child: Icon(action.icon, color: action.color, size: 22),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        action.label,
                        style: TextStyle(fontSize: 14, fontWeight: FontWeight.w600, color: cs.onSurface),
                      ),
                    ),
                  ],
                ),
              ),
            );
          },
        );
      },
    );
  }

  Widget _buildLiveSensorGrid(SensorReading reading) {
    final metrics = [
      {
        'label': 'Temperature',
        'value': reading.temperature.toStringAsFixed(1),
        'unit': '°C',
        'icon': Icons.thermostat,
        'color': AppTheme.primary,
        'progress': ((reading.temperature - 25) / 15).clamp(0.0, 1.0),
        'trend': reading.temperatureTrend ?? 'stable',
        'sensor': 'DHT22',
      },
      {
        'label': 'Pressure',
        'value': reading.pressure.toStringAsFixed(2),
        'unit': 'bar',
        'icon': Icons.speed,
        'color': AppTheme.primary,
        'progress': ((reading.pressure - 0.8) / 0.7).clamp(0.0, 1.0),
        'trend': reading.pressureTrend ?? 'stable',
        'sensor': 'BMP280',
      },
      {
        'label': 'Methane',
        'value': reading.methane.toStringAsFixed(0),
        'unit': 'ppm',
        'icon': Icons.gas_meter,
        'color': AppTheme.secondary,
        'progress': ((reading.methane - 150) / 350).clamp(0.0, 1.0),
        'trend': reading.methaneTrend ?? 'stable',
        'sensor': 'MQ-4',
      },
      {
        'label': 'Level',
        'value': reading.slurryLevel.toStringAsFixed(1),
        'unit': '%',
        'icon': Icons.layers,
        'color': AppTheme.tertiary,
        'progress': (reading.slurryLevel / 100).clamp(0.0, 1.0),
        'trend': reading.slurryTrend ?? 'stable',
        'sensor': 'HC-SR04',
      },
    ];

    return LayoutBuilder(
      builder: (context, constraints) {
        final columns = constraints.maxWidth < 420 ? 1 : 2;
        return GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: columns,
            mainAxisSpacing: 12,
            crossAxisSpacing: 12,
            childAspectRatio: columns == 1 ? 2.2 : 1.1,
          ),
          itemCount: metrics.length,
          itemBuilder: (context, index) {
            final m = metrics[index];
            return MetricCard(
              label: m['label'] as String,
              value: m['value'] as String,
              unit: m['unit'] as String,
              icon: m['icon'] as IconData,
              iconColor: m['color'] as Color,
              status: 'LIVE',
              progress: m['progress'] as double,
              trend: m['trend'] as String,
              lastUpdate: 'Now',
              sensorModel: m['sensor'] as String,
            );
          },
        );
      },
    );
  }

  Widget _buildDailyInsight(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final sensorProv = context.watch<SensorProvider>();
    final isFrench = context.watch<LocaleProvider>().isFrench;
    final reading = sensorProv.latestReading;

    String insight;
    if (reading != null && reading.temperature > 0) {
      if (reading.temperature > 40) {
        insight = isFrench
            ? 'Attention: Température élevée détectée (${reading.temperature.toStringAsFixed(1)}\u00b0C). Vérifier le refroidissement.'
            : 'Warning: High temperature detected (${reading.temperature.toStringAsFixed(1)}\u00b0C). Check cooling.';
      } else if (reading.temperature < 28) {
        insight = isFrench
            ? 'Attention: Température basse (${reading.temperature.toStringAsFixed(1)}\u00b0C). Activité microbienne réduite.'
            : 'Warning: Low temperature (${reading.temperature.toStringAsFixed(1)}\u00b0C). Reduced microbial activity.';
      } else if (reading.pressure > 1.5) {
        insight = isFrench
            ? 'Attention: Pression élevée (${reading.pressure.toStringAsFixed(2)} bar). Vérifier la soupape.'
            : 'Warning: High pressure (${reading.pressure.toStringAsFixed(2)} bar). Check valve.';
      } else {
        insight = isFrench
            ? 'Système opérationnel. Température: ${reading.temperature.toStringAsFixed(1)}\u00b0C, Pression: ${reading.pressure.toStringAsFixed(2)} bar, Méthane: ${reading.methane.toStringAsFixed(0)} ppm.'
            : 'System operational. Temperature: ${reading.temperature.toStringAsFixed(1)}\u00b0C, Pressure: ${reading.pressure.toStringAsFixed(2)} bar, Methane: ${reading.methane.toStringAsFixed(0)} ppm.';
      }
    } else {
      insight = isFrench
          ? 'En attente de données capteur pour générer les insights.'
          : 'Waiting for sensor data to generate insights.';
    }

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: Theme.of(context).colorScheme.outlineVariant.withValues(alpha: 0.5)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                isFrench ? 'Insight du jour' : 'Daily Insight',
                style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.w500,
                  color: cs.onSurface,
                ),
              ),
              const Icon(Icons.lightbulb, color: AppTheme.primary),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            insight,
            style: TextStyle(
              fontSize: 16,
              height: 24 / 16,
              color: AppTheme.subtext(context),
            ),
          ),
          const SizedBox(height: 16),
          OutlinedButton(
            onPressed: () =>
                Navigator.pushNamed(context, AppRoutes.reports),
            style: OutlinedButton.styleFrom(
              minimumSize: const Size(double.infinity, 48),
              side: const BorderSide(color: AppTheme.primary, width: 2),
            ),
            child: Text(isFrench ? 'Voir le rapport complet' : 'View full report'),
          ),
        ],
      ),
    );
  }
}

class _QuickAction {
  final IconData icon;
  final String label;
  final String route;
  final Color color;

  _QuickAction(this.icon, this.label, this.route, this.color);
}
